document
  .getElementsByTagName("button")[0]
  .addEventListener("click", myFunction);

  const quotes = [
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "Life is what happens when you're busy making other plans. - John Lennon",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
    "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
    "Everything you can imagine is real. - Pablo Picasso",
    "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us. - Ralph Waldo Emerson",
    "Life isn't about finding yourself. It's about creating yourself. - George Bernard Shaw",
    "The best way to predict the future is to create it. - Peter Drucker",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "The only person you should try to be better than is the person you were yesterday. - Matty Mullins",
    "You miss 100% of the shots you don't take. - Wayne Gretzky",
    "The only thing we have to fear is fear itself. - Franklin D. Roosevelt",
    "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
    "If you want to lift yourself up, lift up someone else. - Booker T. Washington",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "The best revenge is massive success. - Frank Sinatra",
    "In three words I can sum up everything I've learned about life: it goes on. - Robert Frost",
    "A person who never made a mistake never tried anything new. - Albert Einstein",
    "The only time you fail is when you fall down and stay down. - Stephen Richards",
    "The only journey is the one within. - Rainer Maria Rilke",
    "You become what you believe. - Oprah Winfrey",
    "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "It's not the load that breaks you down, it's the way you carry it. - Lou Holtz",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "The only true wisdom is in knowing you know nothing. - Socrates",
    "Life is really simple, but we insist on making it complicated. - Confucius",
    "The only place success comes before work is in the dictionary. - Vidal Sassoon",
    "The journey of a thousand miles begins with one step. - Lao Tzu",
    "What we think, we become. - Buddha",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "In order to be irreplaceable, one must always be different. - Coco Chanel",
    "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it. - Jordan Belfort",
    "The only person you should try to be better than is the person you were yesterday. - Matty Mullins",
    "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
    "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it. - Jordan Belfort",
    "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
    "The only person you should try to be better than is the person you were yesterday. - Matty Mullins",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "In order to be irreplaceable, one must always be different. - Coco Chanel",
    "What we think, we become. - Buddha",
    "The journey of a thousand miles begins with one step. - Lao Tzu",
    "The only place success comes before work is in the dictionary. - Vidal Sassoon",
    "Life is really simple, but we insist on making it complicated. - Confucius",
    "The only true wisdom is in knowing you know nothing. - Socrates",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "It's not the load that breaks you down, it's the way you carry it. - Lou Holtz",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
    "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll",
    "You become what you believe. - Oprah Winfrey",
    "The only journey is the one within. - Rainer Maria Rilke",
    "The only time you fail is when you fall down and stay down. - Stephen Richards",
    "A person who never made a mistake never tried anything new. - Albert Einstein",
    "In three words I can sum up everything I've learned about life: it goes on. - Robert Frost",
    "The best revenge is massive success. - Frank Sinatra",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "If you want to lift yourself up, lift up someone else. - Booker T. Washington",
    "The only thing we have to fear is fear itself. - Franklin D. Roosevelt",
    "You miss 100% of the shots you don't take. - Wayne Gretzky",
    "The only person you should try to be better than is the person you were yesterday. - Matty Mullins",
    "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
    "In order to be irreplaceable, one must always be different. - Coco Chanel",
    "What we think, we become. - Buddha",
    "The journey of a thousand miles begins with one step. - Lao Tzu",
    "The only place success comes before work is in the dictionary. - Vidal Sassoon",
    "Life is really simple, but we insist on making it complicated. - Confucius",
    "The only true wisdom is in knowing you know nothing. - Socrates",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "It's not the load that breaks you down, it's the way you carry it. - Lou Holtz",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
    "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll",
    "You become what you believe. - Oprah Winfrey",
    "The only journey is the one within. - Rainer Maria Rilke",
    "The only time you fail is when you fall down and stay down. - Stephen Richards",
    "A person who never made a mistake never tried anything new. - Albert Einstein",
    "In three words I can sum up everything I've learned about life: it goes on. - Robert Frost",
    "The best revenge is massive success. - Frank Sinatra",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "If you want to lift yourself up, lift up someone else. - Booker T. Washington",
    "The only thing we have to fear is fear itself. - Franklin D. Roosevelt",
    "You miss 100% of the shots you don't take. - Wayne Gretzky",
    "The only person you should try to be better than is the person you were yesterday. - Matty Mullins",
    "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
    "In order to be irreplaceable, one must always be different. - Coco Chanel",
    "What we think, we become. - Buddha",
    "The journey of a thousand miles begins with one step. - Lao Tzu",
    "The only place success comes before work is in the dictionary. - Vidal Sassoon",
    "Life is really simple, but we insist on making it complicated. - Confucius",
    "The only true wisdom is in knowing you know nothing. - Socrates",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "It's not the load that breaks you down, it's the way you carry it. - Lou Holtz",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
    "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll",
    "You become what you believe. - Oprah Winfrey",
    "The only journey is the one within. - Rainer Maria Rilke",
    "The only time you fail is when you fall down and stay down. - Stephen Richards",
    "A person who never made a mistake never tried anything new. - Albert Einstein",
    "In three words I can sum up everything I've learned about life: it goes on. - Robert Frost",
    "The best revenge is massive success. - Frank Sinatra",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "If you want to lift yourself up, lift up someone else. - Booker T. Washington",
    "The only thing we have to fear is fear itself. - Franklin D. Roosevelt",
    "You miss 100% of the shots you don't take. - Wayne Gretzky",
  ];
  
  console.log(quotes);
  

function myFunction() {
  var num = Math.floor(100 * Math.random());
  document.getElementsByTagName("p")[0].innerHTML=quotes[num];
}
